environment: "local"
createIngress: true

postgres:
  enabled: true
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-work-manager-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

net:
  host: "api.cwb03.test"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://agency.cwb03.test, http://public.cwb03.test, http://employer.cwb03.test"
  DB_CONNECTION_URL: "jdbc:postgresql://work-manager-postgres:5432/local-work-manager-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  FIREBASE_GCP_PROJECT_ID: "dsgov-dev"
  GCP_PROJECT_ID: "cwb03-dev-a1fe"
  CERBOS_URI: "127.0.0.1:3592" #"unix:/sock/cerbos.sock"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/cwb03-dev-a1fe/secrets/cwb03-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/cwb03-dev-a1fe/secrets/cwb03-self-signed-token-private-key/versions/latest}"
  USER_MANAGEMENT_BASE_URL: "http://user-management/um"
  TOKEN_PRIVATE_KEY_SECRET: "cwb03-self-signed-token-private-key"
  TOKEN_ISSUER: "cwb03"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]
  DASHBOARD_URL: "http://public.cwb03.test/dashboard"
  INDIVIDUAL_PROFILE_CLAIM_URL: "http://public.cwb03.test/claim-invitation"
  EMPLOYER_PROFILE_CLAIM_URL: "http://employer.cwb03.test/claim-invitation"
  PUBSUB_EMULATOR_HOST: "pubsub-emulator-service:8085" # set actual "host:port" to enable or false to disable
  PUBSUB_EMULATOR_ENABLED: true # set to true to enable emulator
  # cwb03-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/cwb03-dev-a1fe/topics/DOCUMENT_PROCESSING_INITIATION,projects/cwb03-dev-a1fe/topics/APPLICATION_ROLE_REPORTING,projects/cwb03-dev-a1fe/topics/NOTIFICATION_REQUESTS,projects/cwb03-dev-a1fe/topics/AUDIT_EVENTS_RECORDING
