apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: record
  rules:
    - actions: ["create"]
      roles:
        - transaction-submitter
        - transaction-admin
      effect: EFFECT_ALLOW

    - actions: ["view", "update"]
      roles:
        - transaction-admin
      derivedRoles:
        - transaction-subject
      effect: EFFECT_ALLOW

    - actions: [ "update-admin-data" ]
      roles:
        - transaction-admin
      effect: EFFECT_ALLOW